management:
  endpoint:
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
  trace:
    http:
      include:
        - REQUEST_HEADERS
        - REQUEST_BODY
        - PRINCIPAL
server:
  servlet:
    context-path: /@artifactId@